import PATHS from '@/lib/paths'

const ROUTES = {
    HOME: PATHS.HOME,
    LOGIN: `/${PATHS.LOGIN}`,
    CLAWS: `/${PATHS.CLAWS}`,
    CLAW_DETAIL: `/${PATHS.CLAW_DETAIL}/:id`,
    NEW_CLAW: `/${PATHS.NEW_CLAW}`,
    NEW_CLAW_PROVIDER: `/${PATHS.NEW_CLAW_PROVIDER}`,
    NEW_CLAW_PLAN: `/${PATHS.NEW_CLAW_PLAN}`,
    NEW_CLAW_REVIEW: `/${PATHS.NEW_CLAW_REVIEW}`,
    REDEEM_CODE: `/${PATHS.REDEEM_CODE}`,
    ACCOUNT: `/${PATHS.ACCOUNT}`,
    BILLING: `/${PATHS.BILLING}`,
    ADMIN: `/${PATHS.ADMIN}`,
    MINT_CODES: `/${PATHS.MINT_CODES}`,
    MINT_CODES_PLAN: `/${PATHS.MINT_CODES_PLAN}`,
    MINT_CODES_DETAILS: `/${PATHS.MINT_CODES_DETAILS}`,
    MINT_CODES_REVIEW: `/${PATHS.MINT_CODES_REVIEW}`,
    LICENSE: `/${PATHS.LICENSE}`,
    TERMS: `/${PATHS.TERMS}`,
    PRIVACY: `/${PATHS.PRIVACY}`,
    CHANGELOG: `/${PATHS.CHANGELOG}`,
    WHATS_NEW: `/${PATHS.WHATS_NEW}`,
    BLOG: `/${PATHS.BLOG}`,
    BLOG_POST: `/${PATHS.BLOG}/:slug`,
    AFFILIATE: `/${PATHS.AFFILIATE}`,
    AFFILIATE_PROGRAM: `/${PATHS.AFFILIATE_PROGRAM}`,
    COMPARE: `/${PATHS.COMPARE}`
} as const

export default ROUTES