import PATHS from '@/lib/paths'

const ROUTES = {
    HOME: PATHS.HOME,
    GO: `/${PATHS.GO}`,
    DESKTOP_CHANGELOG: `/${PATHS.DESKTOP_CHANGELOG}`,
    LOGIN: `/${PATHS.LOGIN}`,
    CLAWS: `/${PATHS.CLAWS}`,
    CLAW_DETAIL: `/${PATHS.CLAW_DETAIL}/:id`,
    NEW_CLAW: `/${PATHS.NEW_CLAW}`,
    NEW_CLAW_PROVIDER: `/${PATHS.NEW_CLAW_PROVIDER}`,
    NEW_CLAW_PLAN: `/${PATHS.NEW_CLAW_PLAN}`,
    NEW_CLAW_REVIEW: `/${PATHS.NEW_CLAW_REVIEW}`,
    ACCOUNT: `/${PATHS.ACCOUNT}`,
    BILLING: `/${PATHS.BILLING}`,
    ADMIN: `/${PATHS.ADMIN}`,
    LICENSE: `/${PATHS.LICENSE}`,
    TERMS: `/${PATHS.TERMS}`,
    PRIVACY: `/${PATHS.PRIVACY}`,
    CHANGELOG: `/${PATHS.CHANGELOG}`,
    BLOG: `/${PATHS.BLOG}`,
    BLOG_POST: `/${PATHS.BLOG}/:slug`,
    AFFILIATE: `/${PATHS.AFFILIATE}`,
    AFFILIATE_PROGRAM: `/${PATHS.AFFILIATE_PROGRAM}`,
    COMPARE: `/${PATHS.COMPARE}`
} as const

export default ROUTES