const PATHS = {
    HOME: '/',
    LOGIN: 'login',
    CLAWS: 'claws',
    CLAW_DETAIL: 'claw',
    NEW_CLAW: 'new',
    NEW_CLAW_PROVIDER: 'new/provider',
    NEW_CLAW_PLAN: 'new/plan',
    NEW_CLAW_REVIEW: 'new/review',
    REDEEM_CODE: 'claws/redeem',
    INSTALL_PROGRESS: 'install',
    AIOS: 'aios',
    AIOS_INSTALL: 'aios/install',
    AIOS_INSTALL_PROGRESS: 'aios/install',
    AIOS_DETAIL: 'aios',
    AIOS_INTENT: 'aios',
    ADMIN_ANALYTICS: 'admin/analytics',
    ADMIN_USERS: 'admin/users',
    ADMIN_FLEET: 'admin/fleet',
    ADMIN_REFERRALS: 'admin/referrals',
    ADMIN_BILLING: 'admin/billing',
    ADMIN_CODES: 'admin/codes',
    ADMIN_INSTALL_REPORTS: 'admin/install-reports',
    ADMIN_SETTINGS: 'admin/settings',
    ACCOUNT: 'account',
    BILLING: 'billing',
    ADMIN: 'admin',
    PARTNER: 'partner',
    MINT_CODES: 'admin/codes/mint',
    MINT_CODES_PLAN: 'admin/codes/mint/plan',
    MINT_CODES_DETAILS: 'admin/codes/mint/details',
    MINT_CODES_REVIEW: 'admin/codes/mint/review',
    LICENSE: 'license',
    TERMS: 'terms',
    PRIVACY: 'privacy',
    CHANGELOG: 'changelog',
    WHATS_NEW: 'whats-new',
    BLOG: 'blog',
    AFFILIATE: 'affiliate',
    AFFILIATE_PROGRAM: 'affiliate-program',
    COMPARE: 'full-comparison'
} as const

export default PATHS