const TRUNCATE_LENGTHS = {
    PANEL_NAME: 26,
    PANEL_CLAW_SUBTITLE: 18,
    NODE_AGENT_NAME: 21,
    NODE_CLAW_NAME: 7,
    SIDEBAR_CLAW_NAME: 13,
    SIDEBAR_AGENT_NAME: 11
}

export default TRUNCATE_LENGTHS